### ISSUE TITLE
the URLs to each thread is incorrect

### ISSUE THREAD

**Issue by rdearman** [satanasov/postlove#33]
For example, for the thread titled "Breakthroughs...",

the URL is shown as this:
http://forum.language-learners.org/app.php/postlove/210/viewtopic.php?t=2961

causing this error message:
No route found for "GET /postlove/210/viewtopic.php"

because the correct URL should be this:
http://forum.language-learners.org/viewtopic.php?t=2961

**Comment by Galixte** [comment]
Hi @satanasov,

coul you take a look please?

**Comment by rdearman** [comment]
Works now.
