### ISSUE TITLE
Postlove AJAX error

### ISSUE THREAD

**Issue by DueLearner** [satanasov/postlove#35]
After months of experimenting I finally got this extension "Working" on a live board on 3.1.8, however  when someone clicks on the love button it throws up an "AJAX error notification" After the user refreshes the page it seems to count the "like" anyway. 

Any reason why it'd be returning an AJAX error (most of the time) when someone loves a post but still register the like anyway?

**Comment by dchuk** [comment]
I'm also getting this issue, but in 3.2.2. Any ideas what is causing this?

**Comment by bombcheck** [comment]
Getting this error, too.
