### ISSUE TITLE
The two options "Show number of posts" don't work completly

### ISSUE THREAD

**Issue by Galixte** [satanasov/postlove#7]
Hi,

i test your extension on phpBB 3.1.3.

If i active the three next options :
```
Use provided CSS
```
```
Show number of posts this user has liked
```
```
Show the number of liked user's posts
```
The two last options are displayed in viewtopic, good!

If i active only the two next options :
```
Use provided CSS
```
```
Show number of posts this user has liked
```
The last option is displayed in viewtopic, good!

BUT, if i active only the two next options :
```
Use provided CSS
```
```
Show the number of liked user's posts
```
The last option is not displayed in viewtopic, not good -_-

**Comment by satanasov** [comment]
Fixed in 7b37cab2b68e2c50c7543642b5d9352e60d9ab38
