### ISSUE TITLE
( ! ) Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "notification.type.postlove". in C:\xampp\htdocs\vendor\symfony\dependency-injection\ContainerBuilder.php on line 1060

### ISSUE THREAD

**Issue by Arxero** [satanasov/postlove#77]
Hello, I have just updated from 3.2.3 to current 3.3.1 and this the problem that it will not allow me to login in my board is there something I can do to fix it? Thanks!

![Screenshot_10](https://user-images.githubusercontent.com/30701352/90696873-d036c700-e285-11ea-826c-e1a5785cf95e.png)

Clearing the cache and disabling the extension manually did not help me at all. :X

**Comment by satanasov** [comment]
Did you disable the extensions before updating?

You could try manually removing notification.type.postlove from DB and cleaning cache. Pretty sure there was I had similar issue while testing ...

**Comment by Arxero** [comment]
Thanks that somewhat helped me but a I have tried to follow the update guide of phpbb
https://www.phpbb.com/support/docs/en/3.3/ug/upgradeguide/upgrade32/
 and it turns out it updated properly the phpbb I mean, then what I did was to apply this instructions for but for your extension > https://www.phpbb.com/customise/db/extension/thanks_for_posts_2/faq/2626
using posts_likes to back up

Now all data seems to be where it should be and all is working fast thanks for the relatively fast response, hope this helps others too.
