### ISSUE TITLE
Not all notifications will be received

### ISSUE THREAD

**Issue by Galixte** [satanasov/postlove#8]
Hi,

i test on phpBB 3.1.3.

When a user "A" likes one time two differents posts in two differents topics (or in the same topic) of a same user "B", the user "B" doesn't receive two notifications, but only one about the first post where a "LIKE" was gave.

i hope my sentence is making sense.

**Comment by satanasov** [comment]
fixed in 7b37cab2b68e2c50c7543642b5d9352e60d9ab38
