### ISSUE TITLE
Update for PHPBB v3.3.x

### ISSUE THREAD

**Issue by flatduckrecords** [satanasov/postlove#83]
A forum on which I'm a member recently upgraded from PHPBB 3.2 to 3.3 but the Post Love extension has been [marked as abandoned](https://www.phpbb.com/community/viewtopic.php?t=2246576) on the PHPBB community forum with the advice **not** to install it.

Do you have plans to officially support 3.3.x? And/or would you recommend installing the current version anyway?

It's a great plugin and lots of forum members would *love* to have it enabled again. Are there any particular contributions that might help towards this?

Thank you!

**Comment by Nitrowing** [comment]
We miss this

**Comment by satanasov** [comment]
It's not abandoned and it works on 3.3.x ... I'm using it ...

**Comment by xelalexv** [comment]
It's probably just because there haven't been any commits or releases in quite some time, which is totally fine since this extension appears to be doing all it's supposed to do. Maybe all it takes to get the extension approved again is contacting the extension customisations team, as pointed out [here](https://www.phpbb.com/community/viewtopic.php?p=15716971#p15716971).

**Comment by flatduckrecords** [comment]
> It's not abandoned and it works on 3.3.x ... I'm using it ...

Thanks @satanasov. If you have a moment would you let the [Extension Customisations Team](https://www.phpbb.com/community/memberlist.php?mode=group&g=7331) know the plugin can be marked as 3.3 compatible?

**Comment by kestasjk** [comment]
Yeah I think my mod of this is working on 3.3 also

**Comment by satanasov** [comment]
I sent PM to DavidIQ ... so we wait to remove it from ABD

**Comment by flatduckrecords** [comment]
Thanks @satanasov. We've tested Post Love against the latest PHPBB and it's working well. The forum members are really pleased to have it back, thank you for your help!

**Comment by satanasov** [comment]
I think there are some statistical pages you can now use ...
